url: https://y7kim.github.io
baseurl: /norticnode/

# Site settings
title: Nortic Node
email: contacto@norticnode.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Denis Romasanta
  pic: 1
  position: Ingeniero x 2
  social:
    - title: twitter
      url: https://twitter.com/denisromasanta
    - title: linkedin
      url: https://www.linkedin.com/in/denis-romasanta-rodr%C3%ADguez-0b7a5a116
    - title: github
      url: https://github.com/notanumber11

- name: Pablo Dobarro
  pic: 2
  position: Me importa que quede bonito
  social:
    - title: twitter
      url: https://twitter.com/Zambuseta
    - title: youtube
      url: https://www.youtube.com/user/Zambuseta
    - title: linkedin
      url: https://www.linkedin.com/in/pablodobarro

- name: Armando Nogueira
  pic: 3
  position: Hackerman
  social:
    - title: linkedin
      url: https://es.linkedin.com/in/armando-nogueira-rio-25ba67116
    - title: github
      url: https://github.com/snooze6
      
- name: Diego Reiriz
  pic: 4
  position: Facilitador & Developer
  social:
    - title: twitter
      url: https://twitter.com/diegoreico
    - title: linkedin
      url: https://www.linkedin.com/in/diego-reiriz-cores-33904696
    - title: stack-overflow
      url: http://stackoverflow.com/users/5453610/diego-reiriz-cores
      
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
